#!/bin/sh

# chkconfig: 89 9

# description: zookeeper

source /etc/rc.d/init.d/functions

ZOOKEEPER_BIN='/opt/zookeeper/bin/zkServer.sh'
ZOOKEEPER_CONF='/opt/zookeeper/conf/zoo.cfg'
ZOOKEEPER_LOGS='/zookeeper/logs'
ZOOKEEPER_ENV='/opt/zookeeper/bin/zkEnv.sh'
ZOOKEEPER_USER='zookeeper'
desc="zookeeper daemon"

source $ZOOKEEPER_ENV

start(){
  daemon \
    --user=$ZOOKEEPER_USER \
    ZOO_LOG_DIR=$ZOOKEEPER_LOGS \
    ZOOCFG=$ZOOKEEPER_CONF \
    ZOO_LOG4J_PROP='INFO,ROLLINGFILE' \
    $ZOOKEEPER_BIN start $ZOOKEEPER_CONF
}

stop(){
  $ZOOKEEPER_BIN stop
}

status(){
  echo "Statusing $desc :"
  
}

restart(){
  echo "Restarting $desc :"
  
}

case "$1" in
  start)
    start 
    ;;
  stop)
    stop 
    ;;
  status)
    status 
    ;;
  restart)
    restart
    ;;
  *)
    echo "Usage: service $desc {start|stop|restart|status}"
    ;;
esac